const express = require("express");

const app = express();
const PORT = 3000;

const courses = [
  { id: 1, title: "Full Stack JavaScript" },
  { id: 2, title: "Advanced JavaScript" },
  { id: 3, title: "Express 101" },
  { id: 4, title: "WebD 172" },
];

// Built-in middleware
app.use(express.json());
app.use(express.static("public"));

// Custom middleware
app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

// Plain text route
app.get("/hello", (req, res) => {
  res.send("Hello from Express!");
});

// HTML response
app.get("/about", (req, res) => {
  res.send(`
        <h1>About This Server</h1>
        <p>This page was generated by Express.</p>
    `);
});

// JSON response
app.get("/courses", (req, res) => {
  res.json(courses);
});

app.get("/api/student/:name", (req, res) => {
  const { name } = req.params;
  const courseId = Number(req.query.courseId);

  const course = courses.find((c) => c.id === courseId);

  const student = {
    name: name,
    course: course ? course.title : "Unknown course",
    grade: "A",
  };

  res.json(student);
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
