const express = require("express");

const app = express();
const PORT = 3000;

// Middleware
app.use(express.json());
app.use(express.static("public"));

app.use((req, res, next) => {
    console.log(`${req.method} ${req.url}`);
    next();
});

// Plain text route
app.get("/hello", (req, res) => {
    
    res.send("Hello from Express!");
});

// HTML response
app.get("/about", (req, res) => {
    res.send(`
        <h1>About This Server</h1>
        <p>This page was generated by Express.</p>
    `);
});

// JSON response
app.get("/courses", (req, res) => {
    res.json([
        {
            id: 1,
            title: "Full Stack JavaScript"
        },
        {
            id: 2,
            title: "Advanced JavaScript"
        }
    ]);
});

// Route parameter
app.get("/student/:name", (req, res) => {
    const { name } = req.params;

    res.send(`Welcome, ${name}!`);
});

// Start server
app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});