const express = require("express");

const app = express();
const PORT = 3000;
const courses = [
  {
    id: 1,
    title: "Full Stack JavaScript",
    description:
      "Learn to build web applications using JavaScript, Node.js, and React.",
  },
  {
    id: 2,
    title: "Advanced JavaScript",
    description:
      "Deep dive into advanced JavaScript concepts and best practices.",
  },
  {
    id: 3,
    title: "Node.js Fundamentals",
    description:
      "Learn the basics of building server-side applications with Node.js.",
  },
];

// Middleware
app.use(express.json());
app.use(express.static("public"));

app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

//About route
app.get("/about", (req, res) => {
  res.send(`
    <h1>About the Course Portal</h1>
    <p>This page was generated by Express.</p>
    <p><a href="/">Return Home</a></p>
  `);
});

//Courses route
app.get("/api/courses", (req, res) => {
  res.json(courses);
});

//Course by ID route
app.get("/api/courses/:id", (req, res) => {
  const id = Number(req.params.id);
  const course = courses.find((course) => course.id === id);

  if (!course) {
    return res.status(404).send("Course not found");
  }

  res.json(course);
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
