const express = require("express");

const app = express();
const PORT = 3000;

const courses = [
  { id: 1, title: "WEBD 172" },
  { id: 2, title: "WEBD 171" },
  { id: 3, title: "WEBD 164" },
];

// Built-in middleware
app.use(express.json());

// Custom middleware
app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

app.use(express.static("public"));

// Home page - renders HTML reponse
app.get("/", (req, res) => {
  res.send(`
        <h1>Welcome to My Express Server</h1>
        <p>This page was generated by Express.</p>
        `);
});

// about - HTML response
app.get("/about", (req, res) => {
  res.send(`
    <link rel="stylesheet" href="style.css" />  
    <h1>About Page</h1>
      <p>My Name is: Elizabeth</p>
      <p>Course Name is: WebD 172</p>
      <p>Semester: Fall</p>
    `);
});

// Contact - Plain text route
app.get("/contact", (req, res) => {
  res.send("My email is: eramirez01@sdccd.edu");
});

// Courses - Renders json
app.get("/courses", (req, res) => {
  res.send(courses);
});

// Route Parameters
app.get("/student/:name", (req, res) => {
  const { name } = req.params;
  res.send(`Welcome, ${name}!`);
});

app.get("/course/:courseName", (req, res) => {
  const { courseName } = req.params;
  res.send(`You are vieweing the ${courseName} course.`);
});

app.get("/api/student/:name", (req, res) => {
  const { name } = req.params;
  const courseId = Number(req.query.courseId);

  const course = courses.find((c) => c.id === courseId);

  const student = {
    name: name,
    course: course ? course.title : "Unknown course",
    grade: "A",
  };

  res.json(student);
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
