const express = require("express");

const app = express();
const PORT = 3000;

const courses = [
  { id: 1, title: "WEBD 172" },
  { id: 2, title: "WEBD 171" },
  { id: 3, title: "WEBD 164" },
];

// Built-in middleware
app.use(express.json());
app.use(express.static("public"));

// Custom middleware
app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

app.get("/", (req, res) => {
  res.send(`
        <h1>Welcom to My Express Server</h1>
        <p>This page was generated by Express.</p>
    `);
});

// HTML response
app.get("/about", (req, res) => {
  res.send(`
        <h1>About Page</h1>
        <p>My Name is: Elizabeth</p>
        <p>Course Name is: WebD 172</p>
        <p>Semester: Fall</p>

    `);
});

// Plain text route
app.get("/contact", (req, res) => {
  res.send("My email is: eramirez01@sdccd.edu");
});

app.get("/api/student/:name", (req, res) => {
  const { name } = req.params;
  const courseId = Number(req.query.courseId);

  const course = courses.find((c) => c.id === courseId);

  const student = {
    name: name,
    course: course ? course.title : "Unknown course",
    grade: "A",
  };

  res.json(student);
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
