const getMovies = require("./api");
const express = require("express");
const app = express();
const PORT = 3000;

let movies = [];

// Middleware
app.use(express.json());
app.use(express.static("public"));

app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

//About route
app.get("/about", (req, res) => {
  res.send(`
    <h1>About the Course Portal</h1>
    <p>This page was generated by Express.</p>
    <p><a href="/">Return Home</a></p>
  `);
});

// Movies routes
app.get("/api/movies", (req, res) => {
  res.json(movies);
});

// Movie by ID route
app.get("/api/movies/:id", (req, res) => {
  const id = Number(req.params.id);
  const movie = movies.find((movie) => movie.movie_id === id);

  if (!movie) {
    return res.status(404).json({ message: "Movie not found" });
  }

  res.json(movie);
});

const loadMovies = async () => {
  try {
    movies = await getMovies();
    movies.sort((a, b) =>
      (a.original_title || "").localeCompare(b.original_title || ""),
    );
  } catch (error) {
    console.error("Unable to load movies:", error);
  }
};

loadMovies();

// Start server
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
